### ISSUE TITLE
Implementing Application Dispatching by Path/Subdomain

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [mattupstate/overholt#19]
Hi, I really like the suggested structure of your flas applications... I'm really new to Flask and to the freedom it provides. If you fin the time, can you answer a question?

I'm creating a multi-tenant application using the PostgreSQL schemas, where I will have a public schema + a schema for each tenant. So, I need my application to be something like this: http://www.application.com/tenant/

I'm pretty sure the answer to achieve that is something like this: http://flask.pocoo.org/docs/patterns/appdispatch/#dispatch-by-path

The problem is that I do not know how to best acommodate this in the overholt architecture. Could you give me some tips?

Thank you very much

**Comment by mattupstate** [comment]
Sorry, @DanielFerreiraJorge , but this is not an area for general advice. I'd dip into the Flask mailing list or #pocoo on freenode.
