### ISSUE TITLE
Create Overholt without JavaScript

### ISSUE THREAD

**Issue by sethmoon** [mattupstate/overholt#2]
It would be really helpful if there was a version of this repository without the JavaScript. Perhaps just a static version to better show how Flask would work with more projects.

**Comment by mattupstate** [comment]
@sethmoon I'm not sure I understand your suggestion. Can you be more specific about what would be better if the JavaScript files were removed?

**Comment by sethmoon** [comment]
Well, the current site uses JavaScript to create forms and other data, which is cool and all, but is difficult to understand. Maybe I just have no idea how the forms are being created on the website as there are no template files containing any of the data, I don't even know which file to look in. I also don't know the data is processed (I see the api module, but it seems as though JS is doing all the work with requests).

**Comment by mattupstate** [comment]
The current site does not use JavaScript to create forms. I'm not sure where you're seeing that. If you can point out what you're looking at I can hopefully explain.

**Comment by sethmoon** [comment]
Well this is a bit embarrassing. Without actually testing the code, I assumed this application actually did something in terms of creating stores and what not, but it turns out that all it does is accept requests through the console.

(This is what I get for reading the code an not being able to test it until right now (Just got Vagrant working))
