### ISSUE TITLE
Run api and frontend using manage.py

### ISSUE THREAD

**Issue by roycehaynes** [mattupstate/overholt#20]
How would you go about running both api and frontend apps in development? Specifically, using manage.py.

**Comment by mattupstate** [comment]
I personally wouldn't. I don't see any advantage to running the app(s) via `manage.py` vs `python wsgi.py`.

**Comment by roycehaynes** [comment]
For development purposes, how do you go about running frontend and api? Do you just run the apps with different ports? cc: @mattupstate

**Comment by mattupstate** [comment]
I would set that up in `wsgi.py` and run locally with `python wsgi.py`

**Comment by roycehaynes** [comment]
Cool. Yea, I had a mini brain fart there. Thanks!
