### ISSUE TITLE
Unknown configuration section 'berkshelf'

### ISSUE THREAD

**Issue by gyaresu** [mattupstate/overholt#3]
Hi. Sorry if I'm doing something daft.

```
 ⇒  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'berkshelf'.
```

I even tried:

```
⇒  vagrant plugin install berkshelf
```

I was hoping to follow along to your blog post. There's nothing obvious popping up on a web search. Maybe you've got an idea where I can start to troubleshoot?

Cheers.

**Comment by jonathanchu** [comment]
@gyaresu I got caught up on this too, the correct command is:

```
vagrant plugin install vagrant-berkshelf
```

Cheers!
