### ISSUE TITLE
Basic questions about vagrant

### ISSUE THREAD

**Issue by briancappello** [mattupstate/overholt#6]
Hi,
Thanks very much for taking the time to write this code and share its analysis!
I've not used Vagrant before, and was wondering if you might be able to shed some light on its use within overholt.

From what I can tell after reading the docs and the Vagrantfile, it looks like the virtual machine only gets used for MySQL/Redis.io backend storage - with the actual flask development server running on the local machine.. Is that correct?

I suppose I'm just confused what the exact role vagrant plays in the development stack here, and why more of the web server aspects aren't part of the virtual machine?

Best,

**Comment by mattupstate** [comment]
You're conclusion is correct. The app is run locally and Vagrant is simply used to manage a controlled environment for running the app. This is to make it easier for developers to get started right away. This prevents anyone from needing to configure or install things such as MySQL, Redis, or whatever else the project might need to run on their local machine. Some people prefer to use locally installed versions of such software, and thats fine too. This can easily be done by overriding the config values.

**Comment by briancappello** [comment]
Cool thanks!
